Improve rclone throttle logic

diff --git a/plex/plex-updater.yaml b/plex/plex-updater.yaml
--- a/plex/plex-updater.yaml
+++ b/plex/plex-updater.yaml
@@ -93,10 +93,19 @@ spec:
                   # If all streams are paused, we consider the server to not be active.
                   mediacount="$(awk -F'"' '/<MediaContainer size="[0-9]+">/ {count+=$2}; /<Player[^>]* state="paused"/ {count--}; END {print count}' <<< "${DATA}")"
                   printf '%s\nActivity check reports a count of %i based on the data above\n\n' "$DATA" "$mediacount" >&2
-                  [ $mediacount -gt 5 ] && /opt/bin/rclone rc core/bwlimit rate=1k || /opt/bin/rclone rc core/bwlimit rate=off
-                  if [ $? -ne 0 ]; then
-                      echo "Failed to set bandwidth limit"
-                      exit 1
+                  if [ $mediacount -gt 5 ]; then
+                      /opt/bin/rclone rc core/bwlimit rate=1k
+                      if [ $? -ne 0 ]; then
+                          echo "Failed to set rclone bandwidth limit"
+                          exit 1
+                      fi
+                  fi
+                  if [ $mediacount -lt 4 ]; then
+                      /opt/bin/rclone rc core/bwlimit rate=off
+                      if [ $? -ne 0 ]; then
+                          echo "Failed to remove rclone bandwidth limit"
+                          exit 1
+                      fi
                   fi
                   [ $mediacount -gt 0 ] && exit 0
               else
